### PR TITLE
Add [Divebomb].mcfunction in folder  data --> rcube --> functions/dragon_rework --> attacks --> mad 

### PR DESCRIPTION
**Pull request by veergalrani**
# Made by Boatingbananas 
#
# Called by :
# Ran as : 
#
#
# [In Progress]

### CODE REVIEW

**Comment by MrGenie151** [comment]
Hello! First time seeing the rework project. I would be willing to discuss this over on Discord before I merge the PR. :)
My name on Discord is also mrgenie151, so it shouldn't be too hard to find me

**Comment by veergalrani** [comment]
Sorry, I added this to the wrong thing. I didn't realise this, you can
ignore this but if you would like to know more u can message me on Discord
my name is Boatingbananas

Thanks,
Veer

**Comment by veergalrani** [comment]
Don't intend to merge btw

**Comment by rcubedev** [comment]
This was supposed to be added to a personal fork (CubedNetwork/EnderDragon-Rework).

**Comment by rcubedev** [comment]
Currently, there haven't been many changes.

**Pull request closed without merging**
